photos/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('photos.views',
	url(r'^$', 'toppage', name='photo_toppage'),
	url(r'^(?P<photo_id>[0-9]+)/$', 'single_photo'),
    url(r'^(?P<photo_id>[0-9]+)/comment/$', 'single_photo', name='edit_photo_comment'),
    url(r'^create/$', 'edit_photo'),
)

pystagram/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from photos import urls as photo_urls
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_pystagram.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^photos/', include(photo_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', {
    	'template_name':'login.html'
    }),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
    	'next_page':'/login/'
    }),
    url(r'^signup/$', 'profiles.views.signup'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pystagram_old/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pystagram.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

Categories/models.py
from django.db import models
from categories.models import CategoryBase

# Create your models here.
class Category(models.Model):  
    about = models.TextField(blank=True)
    parent_cat = models.ForeignKey('self', blank=False, null=True)
    slug = models.SlugField(unique=True, help_text = SLUG_HELP)    
    title = models.CharField(max_length = 26, unique=True)

class Post(models.Model):
	category = models.ForeignKey(Category)

photos/models.py
from django.db import models
from django.conf import settings

class Photo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	image_file = models.ImageField()
	is_active = models.BooleanField(default=True)
	tags = models.ManyToManyField('Tag')
	description = models.TextField(null=True)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return u"{0} - '{1}'".format(self.id, self.user)


class Tag(models.Model):
	name = models.CharField(max_length=80)

	def __unicode__(self):
		return u"{0}".format(self.name)


class Comment(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	photo = models.ForeignKey(Photo)
	content = models.TextField(null=False, max_length=500)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_at = models.DateTimeField(auto_now_add=True, auto_now=True)

	def __unicode__(self):
		return u"{0} - '{1}'".format(self.id, self.photo.id)

profiles/models.py
from django.db import models

# Create your models here.
from django.conf import settings

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	gender = models.CharField(max_length=1)
	

photos/forms.py
from django import forms
from .models import Photo, Comment

class PhotoForm(forms.Form):
    image_file = forms.ImageField()
    description = forms.CharField(widget=forms.Textarea)

class PhotoModelForm(forms.ModelForm):
	tags = forms.CharField(
		required=False, max_length=200
	)
	class Meta:
		model = Photo
		fields = ('image_file', 'tags', 'description',)

class CommentModelForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('content',)

profiles/forms.py
from django import forms
from profiles.models import Profile 

class ProfileForm(forms.ModelForm):
	GENDER_CHOICES = (
		('F', 'Female',),
		('M', 'Male',),
	)

	gender = forms.ChoiceField(choices=GENDER_CHOICES)

	class Meta:
		model = Profile
		fields = ('gender',)

		

Categories/views.py
from django.shortcuts import render

# Create your views here.

photos/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from photos.forms import PhotoForm, PhotoModelForm
from photos.models import Photo
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from photos.forms import PhotoModelForm, CommentModelForm

def toppage(request):
	return HttpResponse('hello')

def single_photo(request, photo_id):
	if int(photo_id) == 0:
		return HttpResponseRedirect(reverse('photo_toppage'))
		
	photo = get_object_or_404(Photo, pk=photo_id)

	if request.method == "GET":
		comment_form = CommentModelForm()
	elif request.method == "POST":
		if not request.user.is_authenticated():
			return HttpResponseRedirect(reverse('login_url'))

		comment_form = CommentModelForm(request.POST)
		if comment_form.is_valid():
			_comment = comment_form.save(commit=False)
			_comment.user = request.user
			_comment.photo = photo
			_comment.save()

			return HttpResponseRedirect(request.path)


	return render(
		request, 'single_photo.html',
		{
			'photo': photo,
			'comment_form': comment_form,
		}
)
@login_required
def edit_photo(request) :
	form = PhotoForm()
	if request.method == 'GET':
		form = PhotoForm()
	elif request.method == 'POST':
		form = PhotoModelForm(request.POST,request.FILES)

		if form.is_valid():
	    	# _photo = Photo(
	    	# 	user=request.user,
	    	# 	image_url=request.POST['image_url'],
	    	# 	description=request.POST['description'],
	    	# )
			_photo = form.save(commit=False)
			_photo.user = request.user
			_photo.save()

			return HttpResponseRedirect('/photos/{0}/'.format(_photo.id))
	
	return render(request, 'edit_photo.html', {
				'form': form,
		})
	

profiles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.contrib.auth.forms import UserCreationForm
from profiles.forms import ProfileForm

def signup(request):
	if request.method =='GET':
		user_form = UserCreationForm()
		profile_form = ProfileForm()
	elif request.method == 'POST':
		user_form = UserCreationForm(request.POST)
		profile_form = ProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			_user = user_form.save()
			
			_user.set_password(user_form.cleaned_data['password1'])
			_user.save()

			_profile = profile_form.save(commit=False)
			_profile.user = _user
			_profile.save()

			return HttpResponseRedirect('/photos/create/')

	return render(request, 'signup.html', {
		'user_form': user_form,
		'profile_form': profile_form,
		})

templates/edit_photo.html
{% if form.is_multipart %}
<form method="POST" action="{{request.path}}" enctype="multipart/form-data">
{% else %}
<form method="POST" action="{{request.path}}">
{% endif %}
{% csrf_token %}
{{form.as_p}}

<input type="submit" value="저장" />
</form>

templates/login.html
{% block content %}

{% if form.errors %}
<p>username이나 비밀번호가 틀립니다. </p>
{% endif %}

<form method = "post" action = "{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
	<td>{{ form.username.label_tag }}</td>
	<td>{{ form.username }}</td>
</tr>
<tr>
	<td>{{ form.password.label_tag }}</td>
	<td>{{ form.password }}</td>
</tr>
</table>

<input type = "submit" value="login" />
<input type = "hidden" name = "next" value = "{{ next }}" />
</form>

{% endblock %}

templates/signup.html
<form method="POST" action="{{request.path}}">
{% csrf_token %}
{{user_form.as_p}}
{{profile_form.as_p}}

<input type="submit" value="회원가입" />
</form>

templates/single_photo.html
<html>

<head>
	<title>look picture</title>
</head>

<body>
	{% if request.user.is_authenticated %}
<p>login ok user</p>
{%else%}
<p>login no user</p>
{%endif%}

	<ul>

		<li>{{photo.id}}</li>
		<li><img src="{{photo.image_file.url}}" /></li>
		<li>{{photo.description}}</li>
	</ul>

		{% if photo.comment_set.count %}
			<ul>
			{% for comment in photo.comment_set.all %}
			<li><span>{{comment.user}}</span> : {{comment.content}} ({{comment.updated_at}})</li>
			{% endfor %}
			</ul>
		{% endif %}

		<form method="POST" action="{% url 'edit_photo_comment' photo.id %}">
		{% csrf_token %}

		{{comment_form.as_p}}

		<p><input type="submit" value="댓글 달기" /></p>
	</form>
</body>
</html>